[build]
  base = "/"
  publish = "public"
  command = "hugo --gc"

[build.environment]
  HUGO_VERSION = "0.91.1"

# Use only for builds that publish to docs.nginx.com
[context.production]
  command = "hugo --gc -e production"

# Use only for builds that publish to docs-staging.nginx.com
[context.staging]
  command = "hugo --gc -e staging"

[context.branch-deploy]
  command = "hugo --gc -d public/nginx-for-azure -b $DEPLOY_PRIME_URL/nginx-amplify"

[context.deploy-preview]
  command = "hugo --gc -d public/nginx-for-azure -b $DEPLOY_PRIME_URL/nginx-amplify"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://docs.nginx.com"

[[redirects]]
  from = "/"
  to = "/nginx-amplify/"
  status = 301
  force = true

[[redirects]]
  from = "*"
  to = "/404.html"
  status = 404